name: Build Release

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Release
        uses: softprops/action-gh-release@v1